name: Java CI with Gradle

on:
  push:
    branches: [ "main" ]
    tags: [ "v[0-9]+.[0-9]+.[0-9]+" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    strategy:
      matrix:
        os: [ubuntu-22.04, windows-2022, macos-latest]
    runs-on: ${{ matrix.os }}
    permissions:
      contents: read

    steps:
    - uses: actions/checkout@v4

    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'

    - name: Setup Gradle
      uses: gradle/actions/setup-gradle@417ae3ccd767c252f5661f1ace9f835f9654f2b5 # v3.1.0

    - name: Build with Gradle Wrapper
      working-directory: Game
      run: |
        chmod +x gradlew
        ./gradlew build

    - name: Upload JaCoCo coverage report as a workflow artifact
      uses: actions/upload-artifact@v4.3.1
      with:
        name: jacoco-report-${{ matrix.os }}
        path: Game/core/build/reports/jacoco/test/html/

    - name: Upload library JAR
      uses: actions/upload-artifact@v4.3.1
      with:
        name: lib-${{ matrix.os }}.jar
        path: Game/core/build/libs/*.jar

    - name: Upload Checkstyle report
      uses: actions/upload-artifact@v4.3.1
      if: startsWith(matrix.os, 'ubuntu')
      with:
        name: checkstyle-report
        path: Game/core/build/reports/checkstyle

  dependency-submission:
    runs-on: ubuntu-latest

    permissions:
      contents: write
      security-events: write

    steps:
    - uses: actions/checkout@v4

    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'

    - name: Generate and submit dependency graph
      uses: gradle/actions/dependency-submission@417ae3ccd767c252f5661f1ace9f835f9654f2b5 # v3.1.0
      with:
        build-root-directory: Game
  release:
    runs-on: ubuntu-22.04
    needs: [ "build" ]
    if: startsWith(github.ref, 'refs/tags/')
    permissions:
      contents: write
    steps:
    - name: Download Ubuntu Build Artifact
      uses: actions/download-artifact@v4.1.4
      with:
        name: lib-ubuntu-22.04.jar
    - run: mv Game/core/build/libs/*.jar lib-ubuntu.jar
    - name: Download MacOS Build Artifact
      uses: actions/download-artifact@v4.1.4
      with:
        name: lib-macos-latest.jar
    - run: mv Game/core/build/libs/*.jar lib-macos.jar
    - name: Download Windows Build Artifact
      uses: actions/download-artifact@v4.1.4
      with:
        name: lib-windows-2022.jar
    - run: mv Game/core/build/libs/*.jar lib-windows.jar
    - name: Release
      uses: softprops/action-gh-release@9d7c94cfd0a1f3ed45544c887983e9fa900f0564
      with:
        files: lib*.jar
